### ISSUE TITLE
FileUploader should return the imageUrl 

### ISSUE THREAD

**Issue by arodbits** [anthony2727/radiostreaming-webapp#9]
The imageUrl value should be handle by the FileUploader class and not in the concrete class.

**Comment by anthony2727** [comment]
Close in favor of [#10](https://github.com/anthony2727/radiostreaming-webapp/pull/10)

**Comment by arodbits** [comment]
Closed in favor of [#11](https://github.com/anthony2727/radiostreaming-webapp/pull/11)
